brutal_roasts = [
    "{name}, that wasn’t an attack—it was a cry for help.",
    "Next time, {name}, just stay in bed. The clan will thank you.",
    "Zero stars, {name}? Did you even deploy your troops?",
    "Congratulations, {name}, you’ve set a new record—for failure.",
    "{name}, even the builder base troops are laughing at you.",
    "I didn’t know we were hiring saboteurs, {name}.",
    "If incompetence were an Olympic sport, you’d take gold, {name}.",
    "{name}, you’d do more damage with a feather than that attack.",
    "Are you secretly playing for the enemy, {name}?",
    "The only thing you destroyed, {name}, was our dignity.",
    "I’ve seen better performances from a troop that disconnected, {name}.",
    "Did you even mean to press 'Attack', {name}, or was that an accident?",
    "{name}, I’d recommend a tutorial, but even that won’t save you.",
    "{name}, you’ve officially wasted everyone’s time.",
    "Even the clan castle troops are ashamed of you, {name}.",
    "Your attack strategy must’ve been 'close your eyes and hope', {name}.",
    "If you’re aiming for rock bottom, {name}, you just dug a new hole.",
    "{name}, next time, try attacking the base, not the grass around it.",
    "Even a skeleton trap could’ve stopped your entire army, {name}.",
    "Zero stars, {name}? The enemy clan sends their thanks.",
    "{name}, at this point, we’re just keeping you around for laughs.",
    "Your attack was so bad, we’re submitting it to comedy central, {name}.",
    "Do us a favor, {name}, and attack after the war is over next time.",
    "{name}, you’re single-handedly redefining the term 'dead weight'.",
    "{name}, next time, just drop your troops and log off.",
    "{name}, it takes real talent to fail this spectacularly.",
    "You’ve managed to turn a strategy game into a guessing game, {name}.",
    "The clan isn’t mad, {name}, just… disappointed.",
    "Your attack will go down in history—as a cautionary tale, {name}.",
    "{name}, the only thing you destroyed was your credibility."
    "{name}, I've seen goblins with better plans than you.",
    "Congratulations, {name}, you've redefined rock bottom.",
    "{name}, next time just send a single barbarian—same result, less embarrassment.",
    "{name}, did you drop your troops, or just your hopes?",
    "Even a healer would have done more damage, {name}.",
    "{name}, the enemy base thought it was a peace offering.",
    "{name}, that wasn't an attack—it was an elaborate joke.",
    "Your troops are suing for misuse, {name}.",
    "The replay of your attack, {name}, should be labeled 'cautionary tale.'",
    "{name}, did you deploy your army or just your imagination?",
    "Your attack plan, {name}, seems to have been 'click and pray.'",
    "The only thing you destroyed, {name}, was our chance of winning.",
    "If shame were a resource, {name}, you'd have maxed storages.",
    "{name}, your strategy is what the enemy dreams of.",
    "Even the builders are laughing at you, {name}.",
    "Did you think this was a farming raid, {name}? Because it sure wasn't war-worthy.",
    "Next time, {name}, try attacking with your eyes open.",
    "{name}, your strategy seems to be inspired by surrender.",
    "Even the AI was embarrassed watching your attack, {name}.",
    "The enemy didn't need a strategy to beat you, {name}; you did it for them."
]

roasts = [
    "You’ve managed to turn a strategy game into a guessing game, {name}.",
    "{name}, you hit harder than a wet noodle... but barely.",
    "I've seen toddlers do better than you, {name}.",
    "{name}, you had one job, and you barely did half of it.",
    "If we wanted 1-star attacks, we’d just let my grandma play, {name}.",
    "{name}, you make the goblins look like pro attackers.",
    "Congratulations, {name}, you’ve redefined mediocrity.",
    "{name}, even the practice attacks look better than that mess.",
    "You couldn’t have planned that worse if you tried, {name}.",
    "The town hall was right there, {name}, how did you miss it?",
    "{name}, next time, try attacking with your eyes open.",
    "Was that an attack or a performance art piece, {name}?",
    "Even the enemy clan is laughing at you, {name}.",
    "{name}, you’ve achieved a new low, even for us.",
    "They say practice makes perfect, {name}, so start practicing.",
    "If failing was a competition, {name}, you’d win gold.",
    "{name}, are you even trying, or was that just for fun?",
    "Next time, {name}, just drop the troops and walk away.",
    "That was a textbook example of how not to attack, {name}.",
    "I’ve seen skeleton traps with more strategy than you, {name}.",
    "The enemy’s walls are stronger than your willpower, {name}.",
    "Was that lag, {name}, or are you just bad at this?",
    "The only thing worse than your attack, {name}, is your excuses.",
    "If you tried to sabotage us, {name}, it would look exactly the same.",
    "Remember, {name}, it’s not about winning—it’s about not being you.",
    "{name}, maybe consider switching to farming?",
    "Even the AI is questioning your decisions, {name}.",
    "At least the enemy got some free laughs, {name}.",
    "Next time, {name}, just ask for help… or retire.",
    "You could’ve done better blindfolded, {name}.",
    "Is this Clash of Clans or Clash of Fails, {name}?",
    "Well, {name}, at least you’re consistent… consistently terrible.",
    "You’re the reason we can’t have nice things, {name}.",
    "You’d do more damage if you just sneezed on their base, {name}.",
    "{name}, did you attack or just tickle the defenses?",
    "Well, {name}, at least you didn’t 0-star… this time.",
    "{name}, I’ve seen more coordinated attacks from goblin raids.",
    "If trophies were handed out for effort, {name}, you’d still lose.",
    "Did you attack with troops, {name}, or a gentle breeze?",
    "{name}, next time, try aiming for the base.",
    "Did you confuse the ‘Attack’ button with ‘Surrender,’ {name}?",
    "I’ve seen practice runs that looked more serious than your attack, {name}.",
    "It’s okay, {name}, maybe try watching a strategy video next time.",
    "If attacks were graded, {name}, yours would get a participation award.",
    "Your troops are sending a formal complaint after that attack, {name}.",
    "At least you got one star, {name}. It’s not much, but it’s something.",
    "If humor was your goal, {name}, your attack was a great joke.",
    "Well, {name}, that was an attack... technically.",
    "Did you use strategy, {name}, or just random button presses?",
    "{name}, was your army on vacation during that attack?",
    "Your attack, {name}, was like a free donation to the enemy.",
    "You might want to take a second look at your army composition, {name}.",
    "Did you bring troops, {name}, or just good intentions?",
    "You hit harder than a marshmallow, {name}.",
    "The enemy says thanks for the free loot, {name}.",
    "You’re the reason we need better war planning, {name}.",
    "That attack, {name}, will go down in history… as a cautionary tale.",
    "Maybe next time, {name}, don’t skip troop training day.",
    "Your strategy was as solid as a house of cards, {name}.",
    "Well, {name}, at least you didn’t disconnect mid-attack.",
    "{name}, was that an attack or a sightseeing tour of the enemy base?",
    "Your troops deserved better than that, {name}.",
    "{name}, the town hall was right there. How did you miss it?",
    "Did you attack or just send the enemy a greeting card, {name}?",
    "Your attack, {name}, was like a punchline without a joke.",
    "At least you gave the enemy clan a good laugh, {name}.",
    "{name}, next time try deploying the troops, not just staring at the base.",
    "Even the enemy is wondering what happened during your attack, {name}.",
    "You might want to rethink your spell usage, {name}.",
    "The only thing you destroyed, {name}, was your own morale."
]
